// Branded single-response PDF: a respondent's own copy of what they submitted.
// Client-side only, reuses jsPDF (already a dependency) and the report palette.

import { fill, ink, INK, MUTED, PAPER, REPORT_PALETTE, RULE, stroke } from "./charts";
import { SITE_URL } from "@/lib/site";

export type ResponsePdfQuestion = {
  id: string;
  text: string;
  type: "text" | "choice" | "rating";
};

export async function downloadMyResponsePdf(args: {
  surveyTitle: string;
  surveyDescription?: string | null;
  questions: ResponsePdfQuestion[];
  answers: Record<string, string>;
  submittedAt: string;
  respondentName?: string | null;
}) {
  const { surveyTitle, surveyDescription, questions, answers, submittedAt, respondentName } = args;
  const { default: jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4", compress: true });

  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const margin = 48;
  const contentW = W - margin * 2;
  let y = margin;

  const paint = () => {
    fill(doc, PAPER);
    doc.rect(0, 0, W, H, "F");
  };
  paint();

  const ensure = (h: number) => {
    if (y + h > H - margin - 30) {
      doc.addPage();
      paint();
      y = margin;
    }
  };

  const text = (
    txt: string,
    opts: { size?: number; bold?: boolean; color?: string; indent?: number } = {},
  ) => {
    const size = opts.size ?? 10;
    const leading = size + 5;
    const indent = opts.indent ?? 0;
    doc.setFont("helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(size);
    ink(doc, opts.color ?? INK);
    const lines = doc.splitTextToSize(txt, contentW - indent);
    for (const ln of lines) {
      ensure(leading);
      doc.text(ln, margin + indent, y + size * 0.8);
      y += leading;
    }
  };

  // Header band
  fill(doc, REPORT_PALETTE[0]);
  doc.rect(0, 0, W, 132, "F");
  fill(doc, "#b8c47a");
  doc.roundedRect(margin, 34, 30, 30, 9, 9, "F");
  ink(doc, REPORT_PALETTE[0]);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("C", margin + 10, 55);
  ink(doc, "#e8efe4");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("CAMPUSVERIFY · YOUR SUBMITTED RESPONSE", margin + 42, 47);
  ink(doc, "#ffffff");
  doc.setFontSize(19);
  const titleLines = doc.splitTextToSize(surveyTitle, contentW).slice(0, 2);
  titleLines.forEach((ln: string, i: number) => doc.text(ln, margin, 88 + i * 22));

  y = 156;
  if (surveyDescription) text(surveyDescription, { size: 9, color: MUTED });
  text(`Submitted ${new Date(submittedAt).toLocaleString()}`, { size: 9, color: MUTED });
  if (respondentName) text(`Respondent: ${respondentName}`, { size: 9, color: MUTED });

  y += 6;
  ensure(12);
  stroke(doc, RULE);
  doc.setLineWidth(0.5);
  doc.line(margin, y, W - margin, y);
  y += 14;

  questions.forEach((q, i) => {
    ensure(40);
    text(`Q${i + 1}. ${q.text}`, { size: 10.5, bold: true });
    const raw = answers?.[q.id];
    const value =
      raw == null || String(raw).trim() === ""
        ? "— no answer —"
        : q.type === "rating"
          ? `${String(raw)} / 5`
          : String(raw);
    text(value, { size: 10, color: raw ? INK : MUTED, indent: 14 });
    y += 8;
  });

  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    ink(doc, MUTED);
    doc.text(`Generated by CampusVerify · ${SITE_URL.replace(/^https?:\/\//, "")}`, margin, H - 24);
    doc.text(`Page ${p} of ${total}`, W - margin, H - 24, { align: "right" });
  }

  const name =
    (surveyTitle || "survey").replace(/[^a-z0-9]+/gi, "_").replace(/^_+|_+$/g, "").slice(0, 50) ||
    "survey";
  doc.save(`${name}_my_response.pdf`);
}
