/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminSetupRouteImport } from './routes/admin-setup'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveyIdRouteImport } from './routes/survey.$id'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as BlogStudentSurveyQuestionsGuideRouteImport } from './routes/blog.student-survey-questions-guide'
import { Route as BlogStudentPerceptionSurveysRouteImport } from './routes/blog.student-perception-surveys'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPollsRouteImport } from './routes/_authenticated/polls'
import { Route as AuthenticatedMySurveysRouteImport } from './routes/_authenticated/my-surveys'
import { Route as AuthenticatedManageRouteImport } from './routes/_authenticated/manage'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedFacultyRouteImport } from './routes/_authenticated/faculty'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedBuyCreditsRouteImport } from './routes/_authenticated/buy-credits'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedManageSurveyIdRouteImport } from './routes/_authenticated/manage.$surveyId'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack/webhook'
import { Route as AuthenticatedSurveyIdReportRouteImport } from './routes/_authenticated/survey.$id.report'
import { Route as AuthenticatedSurveyIdAnalyzeRouteImport } from './routes/_authenticated/survey.$id.analyze'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyIdRoute = SurveyIdRouteImport.update({
  id: '/survey/$id',
  path: '/survey/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogStudentSurveyQuestionsGuideRoute =
  BlogStudentSurveyQuestionsGuideRouteImport.update({
    id: '/blog/student-survey-questions-guide',
    path: '/blog/student-survey-questions-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogStudentPerceptionSurveysRoute =
  BlogStudentPerceptionSurveysRouteImport.update({
    id: '/blog/student-perception-surveys',
    path: '/blog/student-perception-surveys',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPollsRoute = AuthenticatedPollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMySurveysRoute = AuthenticatedMySurveysRouteImport.update({
  id: '/my-surveys',
  path: '/my-surveys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManageRoute = AuthenticatedManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFacultyRoute = AuthenticatedFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBuyCreditsRoute = AuthenticatedBuyCreditsRouteImport.update({
  id: '/buy-credits',
  path: '/buy-credits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManageSurveyIdRoute =
  AuthenticatedManageSurveyIdRouteImport.update({
    id: '/$surveyId',
    path: '/$surveyId',
    getParentRoute: () => AuthenticatedManageRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack/webhook',
    path: '/api/public/paystack/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSurveyIdReportRoute =
  AuthenticatedSurveyIdReportRouteImport.update({
    id: '/survey/$id/report',
    path: '/survey/$id/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSurveyIdAnalyzeRoute =
  AuthenticatedSurveyIdAnalyzeRouteImport.update({
    id: '/survey/$id/analyze',
    path: '/survey/$id/analyze',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-setup': typeof AdminSetupRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/index': typeof Char91indexChar93Route
  '/pitch': typeof PitchRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/buy-credits': typeof AuthenticatedBuyCreditsRoute
  '/create': typeof AuthenticatedCreateRoute
  '/faculty': typeof AuthenticatedFacultyRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/manage': typeof AuthenticatedManageRouteWithChildren
  '/my-surveys': typeof AuthenticatedMySurveysRoute
  '/polls': typeof AuthenticatedPollsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/blog/student-perception-surveys': typeof BlogStudentPerceptionSurveysRoute
  '/blog/student-survey-questions-guide': typeof BlogStudentSurveyQuestionsGuideRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$token': typeof RTokenRoute
  '/survey/$id': typeof SurveyIdRoute
  '/manage/$surveyId': typeof AuthenticatedManageSurveyIdRoute
  '/survey/$id/analyze': typeof AuthenticatedSurveyIdAnalyzeRoute
  '/survey/$id/report': typeof AuthenticatedSurveyIdReportRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-setup': typeof AdminSetupRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/index': typeof Char91indexChar93Route
  '/pitch': typeof PitchRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/buy-credits': typeof AuthenticatedBuyCreditsRoute
  '/create': typeof AuthenticatedCreateRoute
  '/faculty': typeof AuthenticatedFacultyRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/manage': typeof AuthenticatedManageRouteWithChildren
  '/my-surveys': typeof AuthenticatedMySurveysRoute
  '/polls': typeof AuthenticatedPollsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/blog/student-perception-surveys': typeof BlogStudentPerceptionSurveysRoute
  '/blog/student-survey-questions-guide': typeof BlogStudentSurveyQuestionsGuideRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$token': typeof RTokenRoute
  '/survey/$id': typeof SurveyIdRoute
  '/manage/$surveyId': typeof AuthenticatedManageSurveyIdRoute
  '/survey/$id/analyze': typeof AuthenticatedSurveyIdAnalyzeRoute
  '/survey/$id/report': typeof AuthenticatedSurveyIdReportRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-setup': typeof AdminSetupRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/index': typeof Char91indexChar93Route
  '/pitch': typeof PitchRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/buy-credits': typeof AuthenticatedBuyCreditsRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/faculty': typeof AuthenticatedFacultyRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/manage': typeof AuthenticatedManageRouteWithChildren
  '/_authenticated/my-surveys': typeof AuthenticatedMySurveysRoute
  '/_authenticated/polls': typeof AuthenticatedPollsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/blog/student-perception-surveys': typeof BlogStudentPerceptionSurveysRoute
  '/blog/student-survey-questions-guide': typeof BlogStudentSurveyQuestionsGuideRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$token': typeof RTokenRoute
  '/survey/$id': typeof SurveyIdRoute
  '/_authenticated/manage/$surveyId': typeof AuthenticatedManageSurveyIdRoute
  '/_authenticated/survey/$id/analyze': typeof AuthenticatedSurveyIdAnalyzeRoute
  '/_authenticated/survey/$id/report': typeof AuthenticatedSurveyIdReportRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-setup'
    | '/auth'
    | '/forgot-password'
    | '/guide'
    | '/index'
    | '/pitch'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/buy-credits'
    | '/create'
    | '/faculty'
    | '/feed'
    | '/manage'
    | '/my-surveys'
    | '/polls'
    | '/profile'
    | '/blog/student-perception-surveys'
    | '/blog/student-survey-questions-guide'
    | '/invite/$token'
    | '/r/$token'
    | '/survey/$id'
    | '/manage/$surveyId'
    | '/survey/$id/analyze'
    | '/survey/$id/report'
    | '/api/public/paystack/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-setup'
    | '/auth'
    | '/forgot-password'
    | '/guide'
    | '/index'
    | '/pitch'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/buy-credits'
    | '/create'
    | '/faculty'
    | '/feed'
    | '/manage'
    | '/my-surveys'
    | '/polls'
    | '/profile'
    | '/blog/student-perception-surveys'
    | '/blog/student-survey-questions-guide'
    | '/invite/$token'
    | '/r/$token'
    | '/survey/$id'
    | '/manage/$surveyId'
    | '/survey/$id/analyze'
    | '/survey/$id/report'
    | '/api/public/paystack/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin-setup'
    | '/auth'
    | '/forgot-password'
    | '/guide'
    | '/index'
    | '/pitch'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/buy-credits'
    | '/_authenticated/create'
    | '/_authenticated/faculty'
    | '/_authenticated/feed'
    | '/_authenticated/manage'
    | '/_authenticated/my-surveys'
    | '/_authenticated/polls'
    | '/_authenticated/profile'
    | '/blog/student-perception-surveys'
    | '/blog/student-survey-questions-guide'
    | '/invite/$token'
    | '/r/$token'
    | '/survey/$id'
    | '/_authenticated/manage/$surveyId'
    | '/_authenticated/survey/$id/analyze'
    | '/_authenticated/survey/$id/report'
    | '/api/public/paystack/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuideRoute: typeof GuideRoute
  Char91indexChar93Route: typeof Char91indexChar93Route
  PitchRoute: typeof PitchRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogStudentPerceptionSurveysRoute: typeof BlogStudentPerceptionSurveysRoute
  BlogStudentSurveyQuestionsGuideRoute: typeof BlogStudentSurveyQuestionsGuideRoute
  InviteTokenRoute: typeof InviteTokenRoute
  RTokenRoute: typeof RTokenRoute
  SurveyIdRoute: typeof SurveyIdRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-setup': {
      id: '/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/$id': {
      id: '/survey/$id'
      path: '/survey/$id'
      fullPath: '/survey/$id'
      preLoaderRoute: typeof SurveyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/student-survey-questions-guide': {
      id: '/blog/student-survey-questions-guide'
      path: '/blog/student-survey-questions-guide'
      fullPath: '/blog/student-survey-questions-guide'
      preLoaderRoute: typeof BlogStudentSurveyQuestionsGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/student-perception-surveys': {
      id: '/blog/student-perception-surveys'
      path: '/blog/student-perception-surveys'
      fullPath: '/blog/student-perception-surveys'
      preLoaderRoute: typeof BlogStudentPerceptionSurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/polls': {
      id: '/_authenticated/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof AuthenticatedPollsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-surveys': {
      id: '/_authenticated/my-surveys'
      path: '/my-surveys'
      fullPath: '/my-surveys'
      preLoaderRoute: typeof AuthenticatedMySurveysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage': {
      id: '/_authenticated/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof AuthenticatedManageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/faculty': {
      id: '/_authenticated/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof AuthenticatedFacultyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/buy-credits': {
      id: '/_authenticated/buy-credits'
      path: '/buy-credits'
      fullPath: '/buy-credits'
      preLoaderRoute: typeof AuthenticatedBuyCreditsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage/$surveyId': {
      id: '/_authenticated/manage/$surveyId'
      path: '/$surveyId'
      fullPath: '/manage/$surveyId'
      preLoaderRoute: typeof AuthenticatedManageSurveyIdRouteImport
      parentRoute: typeof AuthenticatedManageRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack/webhook': {
      id: '/api/public/paystack/webhook'
      path: '/api/public/paystack/webhook'
      fullPath: '/api/public/paystack/webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/survey/$id/report': {
      id: '/_authenticated/survey/$id/report'
      path: '/survey/$id/report'
      fullPath: '/survey/$id/report'
      preLoaderRoute: typeof AuthenticatedSurveyIdReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/survey/$id/analyze': {
      id: '/_authenticated/survey/$id/analyze'
      path: '/survey/$id/analyze'
      fullPath: '/survey/$id/analyze'
      preLoaderRoute: typeof AuthenticatedSurveyIdAnalyzeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedManageRouteChildren {
  AuthenticatedManageSurveyIdRoute: typeof AuthenticatedManageSurveyIdRoute
}

const AuthenticatedManageRouteChildren: AuthenticatedManageRouteChildren = {
  AuthenticatedManageSurveyIdRoute: AuthenticatedManageSurveyIdRoute,
}

const AuthenticatedManageRouteWithChildren =
  AuthenticatedManageRoute._addFileChildren(AuthenticatedManageRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBuyCreditsRoute: typeof AuthenticatedBuyCreditsRoute
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedFacultyRoute: typeof AuthenticatedFacultyRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedManageRoute: typeof AuthenticatedManageRouteWithChildren
  AuthenticatedMySurveysRoute: typeof AuthenticatedMySurveysRoute
  AuthenticatedPollsRoute: typeof AuthenticatedPollsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSurveyIdAnalyzeRoute: typeof AuthenticatedSurveyIdAnalyzeRoute
  AuthenticatedSurveyIdReportRoute: typeof AuthenticatedSurveyIdReportRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBuyCreditsRoute: AuthenticatedBuyCreditsRoute,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedFacultyRoute: AuthenticatedFacultyRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedManageRoute: AuthenticatedManageRouteWithChildren,
  AuthenticatedMySurveysRoute: AuthenticatedMySurveysRoute,
  AuthenticatedPollsRoute: AuthenticatedPollsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSurveyIdAnalyzeRoute: AuthenticatedSurveyIdAnalyzeRoute,
  AuthenticatedSurveyIdReportRoute: AuthenticatedSurveyIdReportRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminSetupRoute: AdminSetupRoute,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuideRoute: GuideRoute,
  Char91indexChar93Route: Char91indexChar93Route,
  PitchRoute: PitchRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogStudentPerceptionSurveysRoute: BlogStudentPerceptionSurveysRoute,
  BlogStudentSurveyQuestionsGuideRoute: BlogStudentSurveyQuestionsGuideRoute,
  InviteTokenRoute: InviteTokenRoute,
  RTokenRoute: RTokenRoute,
  SurveyIdRoute: SurveyIdRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
